logging.debug("This is a debuggging message")
# logging.info("This is a info message for the coders")
# logging.warning("This is a info warning for the coders")
# logging.error("This is an error message")
# logging.critical("This is an critical message")
